---
#
# Ciscoルータにコマンドを打ち込みます
#
# 2018/07/10 初版
#
# Takamitsu IIDA (@takamitsu-iida)

# 設定パラメータ
#
# command ---  コマンドの配列
# networkos --- 装置種別（デフォルトはiosで、現在のところiosしか試していない）
# host --- ターゲットのアドレス
# port --- ポート番号（デフォルトは23）
# user --- ユーザ名
# password --- パスワード
# become --- 管理者モードになるか
# become_pass --- 管理者モードのパスワード

# タスク設定
# delegate_toは必須。localhostもしくは踏み台を指定すること。

# 戻り値
# stdout 配列。送り込んだコマンド配列に対応して格納される。

# 禁止パラメータ
# ansible_connection: network_cli
# これが設定されていると動作しない

- name: execute command on cisco devices
  hosts: tr1  # telnet_routers
  gather_facts: False
  strategy: linear  # free
  serial: 0

  tasks:

    - name: send commands
      # no_log: True
      delegate_to: localhost
      mytelnet:
        # これらはインベントリから自動設定されるので不要
        # network_os: "{{ ansible_network_os }}"
        # host: "{{ ansible_host }}"
        # user: "{{ ansible_user }}"
        # port: "{{ ansible_port }}"
        # password: "{{ ansible_password }}"
        # become: "{{ ansible_become }}"
        # become_pass: "{{ ansible_become_pass }}"
        commands:
          # - command: clear counters gig 2
          #   prompt: '\[confirm\]'
          #   answer: y
          # - show run int gig 2
          - show process cpu | inc CPU
      register: r

    - name: show stdout
      debug:
        msg: |
          {% for s in r.stdout %}
          {{ s }}
          -----
          {% endfor %}

    - name: command history (for debug purpose)
      debug: var=r.command_history

    - name: prompt history (for debug purpose)
      debug: var=r.prompt_history
